server:
  port: 18155
application:
  name: sql-builder-metadata
spring:
  datasource:
    druid:
      #   数据源基本配置
      #username: DATA_METADATA
      #password: 123456789
      #driver-class-name: dm.jdbc.driver.DmDriver
      #url: jdbc:dm://10.0.8.46:5236/DAMENG

      username: tpcuser
      password: oracle
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@10.0.6.101:1521:tpc

      #username: sdc
      #password: Cdsf@119
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #url: jdbc:mysql://db-metadata-govern.sefon.com:53302/data_metadata_er?serverTimezone=Asia/Shanghai&noAccessToProcedureBodies=true&useUnicode=true&characterEncoding=utf8&useCursorFetch=true
      type: com.alibaba.druid.pool.DruidDataSource
      #   Druid数据源配置
      initial-size: 10
      max-active: 30
      min-idle: 5
      max-wait: 28800
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: select 1 from dual
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 100

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml